In [2]:
import pandas as pd
df = pd.read_csv("insurance.csv")
df.head()

   age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

In [4]:
from ml_explain_preprocess.preprocess import explain_preprocess
processed_df, report = explain_preprocess(df, report_format = 'text', visual = True)

In [6]:
print(report)

--------------- Preprocessing Report ----------------

Step: FILL
Explanation: Missing value handling (imputation) fills in gaps in the data to ensure machine learning models can process it. Missing data can occur due to errors or incomplete collection.
Parameters used: Strategy: auto, Columns: All with missing
Impact: Handled 0 missing values (0.0% of data).
Statistics:
missing_before: {}
missing_after: {}
strategies: {}
Tips for Beginners: Choose 'median' for numerical data with outliers, 'mean' for normally distributed data, or 'mode' for categorical data. Always check how much data is missing before imputing.
---------------------------
Step: ENCODE
Explanation: Encoding converts categorical data (e.g., 'Male'/'Female') into numbers so machine learning models can understand it. One-hot encoding creates new columns for each category, while label encoding assigns numbers to categories.
Parameters used: Method: auto, Columns: ['sex', 'smoker', 'region']
Impact: Transformed 3 categorical columns, added 2 new columns.
Statistics:
unique_before: {'sex': '2 unique values', 'smoker': '2 unique values', 'region': '4 unique values'}
unique_after: {'sex': 'See new columns', 'smoker': 'See new columns', 'region': 'See new columns'}
methods: {'sex': 'onehot', 'smoker': 'onehot', 'region': 'onehot'}
new_columns: {'sex': ['sex_male'], 'smoker': ['smoker_yes'], 'region': ['region_northwest', 'region_southeast', 'region_southwest']}
Tips for Beginners: Use one-hot encoding for low-cardinality categories (e.g., <10 unique values) to avoid implying order. Label encoding is better for high-cardinality or ordinal data.
---------------------------
Step: SCALE
Explanation: Scaling adjusts numerical features to a common range (e.g., 0 to 1) so that machine learning models treat all features equally. MinMax scales to [0,1], Standard scales to mean=0, std=1, Robust is outlier-resistant.
Parameters used: Method: minmax, Columns: ['age', 'bmi', 'children', 'charges', 'sex_male', 'smoker_yes', 'region_northwest', 'region_southeast', 'region_southwest']
Impact: Scaled 9 numerical columns to minmax range.
Statistics:
before: {'age': 'Min: 18.00, Max: 64.00, Mean: 39.21, Std: 14.05', 'bmi': 'Min: 15.96, Max: 53.13, Mean: 30.66, Std: 6.10', 'children': 'Min: 0.00, Max: 5.00, Mean: 1.09, Std: 1.21', 'charges': 'Min: 1121.87, Max: 63770.43, Mean: 13270.42, Std: 12110.01', 'sex_male': 'Min: 0.00, Max: 1.00, Mean: 0.51, Std: 0.50', 'smoker_yes': 'Min: 0.00, Max: 1.00, Mean: 0.20, Std: 0.40', 'region_northwest': 'Min: 0.00, Max: 1.00, Mean: 0.24, Std: 0.43', 'region_southeast': 'Min: 0.00, Max: 1.00, Mean: 0.27, Std: 0.45', 'region_southwest': 'Min: 0.00, Max: 1.00, Mean: 0.24, Std: 0.43'}
after: {'age': 'Min: 0.00, Max: 1.00, Mean: 0.46, Std: 0.31', 'bmi': 'Min: 0.00, Max: 1.00, Mean: 0.40, Std: 0.16', 'children': 'Min: 0.00, Max: 1.00, Mean: 0.22, Std: 0.24', 'charges': 'Min: 0.00, Max: 1.00, Mean: 0.19, Std: 0.19', 'sex_male': 'Min: 0.00, Max: 1.00, Mean: 0.51, Std: 0.50', 'smoker_yes': 'Min: 0.00, Max: 1.00, Mean: 0.20, Std: 0.40', 'region_northwest': 'Min: 0.00, Max: 1.00, Mean: 0.24, Std: 0.43', 'region_southeast': 'Min: 0.00, Max: 1.00, Mean: 0.27, Std: 0.45', 'region_southwest': 'Min: 0.00, Max: 1.00, Mean: 0.24, Std: 0.43'}
method: {'age': 'minmax', 'bmi': 'minmax', 'children': 'minmax', 'charges': 'minmax', 'sex_male': 'minmax', 'smoker_yes': 'minmax', 'region_northwest': 'minmax', 'region_southeast': 'minmax', 'region_southwest': 'minmax'}
Tips for Beginners: Use scaling for algorithms sensitive to feature magnitudes (e.g., SVM, KNN, neural networks). MinMax is good for bounded ranges, Standard for normally distributed data.
---------------------------
Step: OUTLIERS
Explanation: Outliers are extreme values that differ significantly from most data points. They can skew model training. IQR uses quartiles to detect outliers, z-score uses standard deviations.
Parameters used: Method: iqr, Threshold: 1.5, Action: remove, Columns: ['age', 'bmi', 'children', 'charges', 'sex_male', 'smoker_yes', 'region_northwest', 'region_southeast', 'region_southwest']
Impact: Processed 283 outliers accross 9 columns.
Statistics:
outliers_detected: {'age': '0 outliers (0.0%)', 'bmi': '9 outliers (0.7%)', 'children': '0 outliers (0.0%)', 'charges': '138 outliers (10.3%)', 'sex_male': '0 outliers (0.0%)', 'smoker_yes': '136 outliers (10.2%)', 'region_northwest': '0 outliers (0.0%)', 'region_southeast': '0 outliers (0.0%)', 'region_southwest': '0 outliers (0.0%)'}
count_affected: {'age': 'Removed 0 rows', 'bmi': 'Removed 9 rows', 'children': 'Removed 0 rows', 'charges': 'Removed 138 rows', 'sex_male': 'Removed 0 rows', 'smoker_yes': 'Removed 136 rows', 'region_northwest': 'Removed 0 rows', 'region_southeast': 'Removed 0 rows', 'region_southwest': 'Removed 0 rows'}
Tips for Beginners: Remove outliers for small datasets or sensitive models (e.g., linear regression). Clip outliers to keep data but reduce their impact. Always inspect outliers to ensure they're not meaningful.
---------------------------
Step: SELECT
Explanation: Feature selection removes columns with low variance (i.e., nearly constant values) because they provide little information for models. Variance measures how spread out data is.
Parameters used: Variance Threshold: 0.01, Columns: ['age', 'bmi', 'children', 'charges', 'sex_male', 'smoker_yes', 'region_northwest', 'region_southeast', 'region_southwest']
Impact: Dropped 2 low variance columns.
Statistics:
columns_before: ['age', 'bmi', 'children', 'charges', 'sex_male', 'smoker_yes', 'region_northwest', 'region_southeast', 'region_southwest']
dropped: ['charges', 'smoker_yes']
variances: {'age': 'Variance: 0.0934', 'bmi': 'Variance: 0.0252', 'children': 'Variance: 0.0594', 'charges': 'Variance: 0.0086', 'sex_male': 'Variance: 0.2500', 'smoker_yes': 'Variance: 0.0000', 'region_northwest': 'Variance: 0.1892', 'region_southeast': 'Variance: 0.1892', 'region_southwest': 'Variance: 0.1883'}
columns_after: ['age', 'bmi', 'children', 'sex_male', 'region_northwest', 'region_southeast', 'region_southwest']
Tips for Beginners: Use a low threshold to keep more features, higher to be stricter. Check dropped columns to ensure no important data is lost.
---------------------------

In [9]:
processed_df.head()

,age,bmi,children,sex_male,region_northwest,region_southeast,region_southwest
1,0.000000,0.479150,0.2,1.0,0.0,1.0,0.0
2,0.217391,0.458434,0.6,1.0,0.0,1.0,0.0
3,0.326087,0.181464,0.0,1.0,1.0,0.0,0.0
4,0.304348,0.347592,0.0,1.0,1.0,0.0,0.0
5,0.282609,0.263115,0.0,0.0,0.0,1.0,0.0